### PR TITLE
Adding a condition number checker to raise warnings if it is so.

### PR DESCRIPTION
**Pull request by adam2392**
This would address issues where potentially a data matrix is ill-conditioned. Can happen when data is not normalized properly, but it would at least alert the user that such a situation occurred.

It passes all unit tests, and also includes a warning statement that suggests alternatives:
- preprocess data (normalization, etc.)
- possibly augmenting data matrix with stacking 
- apply regularization (this would be nice to implement?)

### CODE REVIEW

**Comment by adam2392** [comment]
#107 is partially addressed here.

**Comment by adam2392** [comment]
I don't know if necessary to add to the rest of the fit functions, or just here. 

If so, perhaps I could migrate this into function "_col_major_2darray(X)"?

**Comment by mtezzele** [comment]
Dear @adam2392 thank you very much for this PR. 
I think it is best to migrate this into the `_col_major_2darray(X)`method. Moreover, can you please make it work also for py2.7? We will end up the support for py2.7 in the near future but in the meantime we do our best ;)

**Comment by adam2392** [comment]
@mtezzele migrated and fixed the warning string! (I think that works?) :p Moved over to py3.6+ awhile ago, so always iffy on the syntax.

**Comment by mtezzele** [comment]
Thank you very much @adam2392 !

**Pull request merged**
