### PR TITLE
Tutorial for cDMD 

### PR DESCRIPTION
**Pull request by joshmyersdean**
This tutorial demonstrates how to use both `cDMD` and `DMD` for background modeling. The tutorial includes a `README` as well with places to change parameters in order to observe the effect on performance (measured by F1 score and mIoU). Note that the videos will not render unless the `ipynb` file is opened either locally or in Colab.

### CODE REVIEW

**Comment by fAndreuzzi** [comment]
Thank you @joshmyersdean! The README is also very useful. I'm going to make some minor stylistic changes, and then I'll pass the ball to the rest of the team.

**Comment by mtezzele** [comment]
Thank you @joshmyersdean! I kindly ask you to uniform the file with 4 spaces for every level of indentation. Moreover, could you please adjust the formatting of the titles in the notebook (correct section level, now there are long sentences in bold).

**Comment by fAndreuzzi** [comment]
@joshmyersdean I'm working now on the notebook, will push some changes to your branch in some minutes, please do not make changes now in order to avoid git conflicts.

**Comment by joshmyersdean** [comment]
Sounds great, thank you!

**Comment by fAndreuzzi** [comment]
Thanks for waiting @joshmyersdean, I'm done with my changes. I fixed your indentation, added some headers with titles here and there, fixed some plots (for instance the last one, I think it's better and more expressive to plot only the first 6 modes/dynamics). Let me know what you think! (In case we can revert to the previous version by dropping the last commit).

Just one question, what is the purpose of the `Colab` button on top? It leads to a 404 error page for me.

**Comment by joshmyersdean** [comment]
Thank you @fAndreuzzi, I think it looks great! The `Colab` button _should_ open the notebook in Google Colab once the changes are merged (it relies on the path to the notebook being `https://github.com/mathLab/PyDMD/blob/master/tutorials/tutorial12/tutorial-12-cdmd.ipynb`) but I'm not offended if you think it is best to leave it out.

**Comment by mtezzele** [comment]
Please make sure the `py` file is consistent with the notebook.

**Comment by joshmyersdean** [comment]
@mtezzele Done, using `nbconvert`.

**Comment by fAndreuzzi** [comment]
@joshmyersdean Yeah I would leave it out just to be consistent with the other tutorials, if we decide in the future to add the button to all the files under `tutorials` it won't be a big change.

**Comment by joshmyersdean** [comment]
@mtezzele Sounds great!

**Comment by fAndreuzzi** [comment]
I removed the Colab button, the tutorial is okay now for me. Thank you @joshmyersdean!

**Pull request merged**
